name: GitHub CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Configure database
        run: |
          cp config/database.yml.example config/database.yml
          sed -i "s/database:.*/database: ticket_star_app_test/" config/database.yml

      - name: Set up Heroku CLI
        uses: actions/heroku@v4
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Create test database
        run: |
          heroku pg:reset --confirm your-heroku-app-name --app your-heroku-app-name
          heroku run rake db:migrate --app your-heroku-app-name

      - name: Run tests
        run: bundle exec rspec
